# Generated by Django 2.0 on 2021-01-05 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nom', models.CharField(help_text='Ingrese el nombre de la categoria', max_length=200, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null='True', upload_to='perfil')),
                ('titulo', models.CharField(help_text='Ingrese el nombre de la imagen', max_length=100, null='True')),
                ('descripcion', models.CharField(help_text='Ingrese su descripcion', max_length=1000, null='True')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, null='True')),
                ('user', models.ForeignKey(blank='True', on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
