# Generated by Django 2.0 on 2021-01-06 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210105_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idImagen', models.ForeignKey(blank='True', on_delete='models.CASCADE', to='users.Imagen')),
                ('user', models.ForeignKey(blank='True', on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idImagen', models.ForeignKey(blank='True', on_delete='models.CASCADE', to='users.Imagen')),
                ('user', models.ForeignKey(blank='True', on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
