# Generated by Django 2.0 on 2021-01-06 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorito_tarde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='user',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
