# Generated by Django 2.0 on 2021-01-06 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210106_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='idImagen',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='users.Imagen'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='user',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarde',
            name='idImagen',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='users.Imagen'),
        ),
        migrations.AlterField(
            model_name='tarde',
            name='user',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
